### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by VictorioBerra** [stefanoschrs/auth0-actions-as-code#2]
Docs should show a couple things:

- You need to expose secrets as env vars to the action in order to use them:
- You need to specify the action version (I got an error without it) IE: `@v1.0.0`
- Also document new actionsRuntime input

```yaml
    - name: Deploy Trigger Code
      uses: stefanoschrs/auth0-actions-as-code@v1.0.0
      env:
        API_KEY: ${{ secrets.API_KEY }}
      with:
        auth0_client_id: ${{ secrets.AUTH0_CLIENT_ID }}
        auth0_client_secret: ${{ secrets.AUTH0_CLIENT_SECRET }}
        auth0_tenant_domain: ${{ secrets.AUTH0_TENANT_DOMAIN }}
        config_path: ./deployment-config.yml
        actions_runtime: 'node22'
```
